### ISSUE TITLE
docker build fails as it takes a "/" in the image tag

### ISSUE THREAD

**Issue by vikas027** [pmyjavec/horatio#3]
I have a very simple `Dockerfile` for testing.

```
$ cat Dockerfile
FROM alpine:3.4
ENV TIMEZONE=Australia/Sydney
$
```

`horatio` fails as it takes a "/" in the image tag. I am experiencing this issue in ruby versions 2.2.2 and 2.3.0.
```bash
$ cat horatio.json
{
  "name": "misc-project",
  "version": "0.0.1"
}
$

$ horatio
I, [2016-09-14T15:22:52.506204 #32669]  INFO -- : detected horatio.json
I, [2016-09-14T15:22:52.511924 #32669]  INFO -- : Running Docker build for misc-project-0.0.1
I, [2016-09-14T15:22:52.511990 #32669]  INFO -- : validating passed in version
I, [2016-09-14T15:22:52.512051 #32669]  INFO -- : validating passed in name
I, [2016-09-14T15:22:52.516943 #32669]  INFO -- : latest revision is a198e59
I, [2016-09-14T15:22:52.521409 #32669]  INFO -- : executing command: docker build -t /misc-project:0.0.1-a198e59 .
F, [2016-09-14T15:22:52.645387 #32669] FATAL -- : execution of `docker build -t /misc-project:0.0.1-a198e59 .` failed output from STDERR was:
 invalid argument "/misc-project:0.0.1-a198e59" for t: Error parsing reference: "/misc-project:0.0.1-a198e59" is not a valid repository/tag
See 'docker build --help'.

 STDOUT was:
  (RuntimeError)
/Users/vikas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/horatio-0.1.7/lib/horatio.rb:55:in `run_sh'
/Users/vikas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/horatio-0.1.7/lib/horatio/releaser.rb:35:in `run'
/Users/vikas/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/horatio-0.1.7/bin/horatio:29:in `<top (required)>'
/Users/vikas/.rbenv/versions/2.3.0/bin/horatio:23:in `load'
/Users/vikas/.rbenv/versions/2.3.0/bin/horatio:23:in `<main>'
$
```

**Comment by vikas027** [comment]
Looks like it is required to use a `-r` or `--registry` switch.

**Comment by pmyjavec** [comment]
Thanks for reporting Vikas, I'll have a look at this soon!

**Comment by vikas027** [comment]
Thanks :+1:
